name = "pb"
compatibility_date = "2023-01-28"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = false
main = "src/index.js"

rules = [
  { type = "Text", globs = [ "*/frontend/**", "*/doc/**" ], fallthrough = true }
]

#----------------------------------------
# lines below are what you should modify
#----------------------------------------

[[routes]]
# Refer to https://developers.cloudflare.com/workers/wrangler/configuration/#routes
pattern = "p.g3r.top"
custom_domain = true

[[kv_namespaces]]
binding = "PB"  # do not touch this
id = "2a489d161ca44b2293fa0f8abdecad8c"  # id of your KV namespace

[vars]
# must be consistent with your routes
BASE_URL = "https://p.g3r.top"

# url to repo, displayed in the index page
REPO = "https://github.com/genzj/pastebin-worker"

# url to the favicon
FAVICON = "data:image/x-icon;base64,AAABAAEAEBAQAAEABAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAACE2egAAAAAAADCIAAAAE8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEREREREzMREREAABETMxEREzMzAiIjERETMDMDMyMRERMwMwIjIiEREwADAzMzIRETMDMzIiIwEREzMzAAIiAREREgAzACMxEREAAAAAADEREAMDADAwAREQAwIAIDABERATMzMzMQEREBIzMzMhAREREiIiIiERERERIiIiERH/xwAA4ccAAMAHAADABwAAwAMAAMADAADAAQAA4AEAAPgBAADwAQAA4AEAAOABAADoBQAA6AUAAPgHAAD8DwAA"

FAVICON_TYPE = "image/x-icon"

# the name displayed in TOS
TOS_MAINTAINER = "genzj"

# the email displayed in TOS
TOS_MAIL = "pb@g3r.top"

# Cache-Control max-age for static pages
CACHE_STATIC_PAGE_AGE = 7200

# Cache-Control max-age for static pages
CACHE_PASTE_AGE = 600
